CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('make a web App',1,'Using Javascript','2019-05-12');

INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('make and app',1,'Using Darck','2019-05-13');

INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('make a Desktop app',2,'Using C++','2019-05-14');

--insert taks data
INSERT INTO tasks(name,done,projectId)
    VALUES('donwload Vuejs',false,1);

INSERT INTO tasks(name,done,projectId)
    VALUES('Create Ui web',false,1);

INSERT INTO tasks(name,done,projectId)
    VALUES('donwload Fluter',false,2);

INSERT INTO tasks(name,done,projectId)
    VALUES('Desing UI',false,2);